name: 1. Basic Workflow
on:
  workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Starting workflow
        run: echo "Starting first workflow"

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: List the content of repo
        run: ls ${{ github.workspace }}