name: 1. Basic Workflow
on:
  workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Starting workflow
        run: echo "Starting first workflow"

      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: List the content of repo
        run: |
          echo "Lista de archivos dentro del repo"
          ls ${{ github.workspace }}
      
      - name: Instalando python
        uses: actions/setup-python@v4
        with:
            python-version: '3.11'